version: '3.1'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crawler-api
    command:
      - ./crawler
      - api
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_COLLECTION: ${MONGODB_COLLECTION}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_HOST: ${MONGODB_HOST}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
      - mongo-express

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_ROOT_DATABASE: ${MONGODB_DATABASE}

  mongo-express:
    image: mongo-express
    container_name: mongodb-express
    restart: always
    ports:
      - ${MONGODB_EXPRESS_PORT}:${MONGODB_EXPRESS_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_EXPRESS_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:${MONGODB_PORT}/

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    depends_on:
      - prometheus

volumes:
  prometheus-data: