{
 "title": "Dashboards",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Links count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(crawler_links_count_total{}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Links error count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(crawler_links_error_count_total{}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delta time to process links",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(crawler_delta_time_to_process_links_bucket{}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(crawler_delta_time_to_process_links_bucket{}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(crawler_delta_time_to_process_links_bucket{}[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}